Add option to specify a log directory for game server logs
Griffon26/taserver pull request #106
Opened 2021-03-15 23:21 UTC by chickenbellyfin

taserver currently tries to query My Documents using the Windows API. This can fail and throw an error if there is no user directory, such as with a system account used for running services. This change allows us to override with a optional custom log directory, with the default being My Documents.

2021-03-16 18:41 UTC, Griffon26 requested changes
As discussed:

- let's make the data dir configurable from the command line
- let the logs dir always be a subdir of the data dir
- make sure all logs, not just the TA ones, end up in the new dir

2021-03-16 18:41 UTC, Griffon26 commented on data/gameserverlauncher.ini
> +# log_dir = C:\CustomLogDir
Let's put it above controller_dll and under dir so that the controller_config related content is together.

2021-03-20 13:49 UTC, Griffon26 reviewed
What did you do for testing it? Did you start everything up?
And did you test it both with and without specifying the argument?

2021-03-20 13:49 UTC, Griffon26 commented on data/logs/.gitignore
> +/*.log
add a newline

2021-03-20 13:49 UTC, Griffon26 commented on login_server/player/loadouts.py
> +        default_loadouts_file = os.path.join(self.data_root, 'defaults', 'default_loadouts_%s.json' % self.game_setting_mode)
I think we have to move these defaults files out of the data dir, because those are files you will never want to change.

2021-03-20 23:34 UTC, chickenbellyfin commented
Testing methodology:

Without --data-root
- Started authbot successfully
- Copied taserver dir into taserver-tmp, and set port_offset there to 2
    - ran firewall & login server from taserver-tmp
    - ran firewall & game server from taserver
    - connected to local login server and joined local game server
    - confirmed account data (level, password, loadouts)
    - no errors in logs

With --data-root
- started authbot successfully
- Copied taserver\data into C:\taserver_data\data_game and C:\taserver_data\data_login
- rename taserver\data so that it would be unreadable (should not be accessed when --data-root is set)
- port_offset in data_login=2
- Started firewall and login server with --data-root=C:\taserver_data\data_login
- Started firewall and game server with --data-root=C:\taserver_data\data_game
- connected & joined game locally, confirmed account data loaded
- no errors in logs

confirmed in all cases that logs for firewall, authbot, game server, tribes, and login server show up in the correct logs/ directories

2021-03-24 20:59 UTC, Griffon26 commented
Two more things and then I think it's ready:
* squash the "data" commit into the previous one
* update hosting_multiple_game_servers.md to make use of this feature instead of copying everything

2021-03-25 19:20 UTC, Griffon26 approved these changes

2021-03-25 19:20 UTC, merged