Launch using wine on linux
Griffon26/taserver pull request #119
Opened 2022-04-17 16:07 UTC by chickenbellyfin

changes:
- move process handling into GameServerProcess class
- implement WineGameServerProcess for linux
- add script to download InjectorStandalone.exe from TribesLauncherSharp

Tested on windows & linux (ubuntu 20.04)

2022-04-18 07:56 UTC, ToddButler93 reviewed
Tested and working on Windows.

Unable to test on Linux at this stage.

2022-11-14 19:43 UTC, Griffon26 requested changes

2022-11-14 19:43 UTC, Griffon26 commented on game_server_launcher/gameserverprocess.py
> +  """
Please fix indentation in this file

2022-11-14 19:43 UTC, Griffon26 commented on game_server_launcher/winegameserverprocess.py
> +  """
Fix indentation here as well. 4 spaces

2022-11-19 22:57 UTC, Griffon26 approved these changes

2022-11-19 22:57 UTC, merged